[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cgt_bandits"
version = "2.1.0"
authors = [
  { name="Tomas Votroubek", email="votroto1@fel.cvut.cz" },
]
description = "Tools for the CGT bandits tree homework"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
]

[project.optional-dependencies]
gambit = [
    "pygambit == 16.4.*"
]
dot = [
    "pydot == 4.0.*"
]
dev = [
    "pygambit == 16.4.*",
    "pydot == 4.0.*",
    "pytest == 8.4.*"
]